#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: foxcpp/maddy
  pullPolicy: IfNotPresent
  tag: "0.4.4"

service:
  port:
    name: smtprelay
    port: 25

additionalServices:
  - name: imap
    port: 143
  - name: smtp
    port: 587
  - name: imaptls
    port: 993

ingress:
  enabled: false

strategy:
  type: Recreate

# https://hub.docker.com/r/foxcpp/maddy
env:
  # -- MX hostname
  MADDY_HOSTNAME: mx.example.org
  # -- Domain to handle messages for
  MADDY_DOMAIN: example.org

pki:
  certManager:
    enabled: false
    issuerName: letsencrypt-prod
    issuerKind: ClusterIssuer

persistence:
  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 5Gi

extraVolumes:
  - name: tls-cert
    secret:
      secretName: acme-crt-secret

extraVolumeMounts:
  - mountPath: /etc/ssl/
    name: tls-cert

# The main configuration file for maddy
config:
  # If set to 'values', the configuration will be read from these values.
  # Otherwise you have to mount a volume to /data containing the configuration files.
  mode: values

  # See https://github.com/foxcpp/maddy/blob/master/maddy.conf for the config sample file
  config: |
    $(local_domains) = $(primary_domain)

    auth.pass_table local_authdb {
        table sql_table {
            driver sqlite3
            dsn credentials.db
            table_name passwords
        }
    }

    storage.imapsql local_mailboxes {
        driver sqlite3
        dsn imapsql.db
    }

    hostname $(hostname)

    msgpipeline local_routing {

        destination postmaster $(local_domains) {
            modify {
                replace_rcpt regexp "(.+)\+(.+)@(.+)" "$1@$3"
                replace_rcpt file /etc/maddy/aliases
            }

            deliver_to &local_mailboxes
        }

        default_destination {
            reject 550 5.1.1 "User doesn't exist"
        }
    }

    smtp tcp://0.0.0.0:25 {
        limits {
            all rate 20 1s
            all concurrency 10
        }

        dmarc yes
        check {
            require_mx_record
            dkim
            spf
        }

        source $(local_domains) {
            reject 501 5.1.8 "Use Submission for outgoing SMTP"
        }
        default_source {
            destination postmaster $(local_domains) {
                deliver_to &local_routing
            }
            default_destination {
                reject 550 5.1.1 "User doesn't exist"
            }
        }
    }

    submission tls://0.0.0.0:465 tcp://0.0.0.0:587 {
        limits {
            all rate 50 1s
        }

        auth &local_authdb

        source $(local_domains) {
            destination postmaster $(local_domains) {
                deliver_to &local_routing
            }
            default_destination {
                modify {
                    dkim $(primary_domain) $(local_domains) default
                }
                deliver_to &remote_queue
            }
        }
        default_source {
            reject 501 5.1.8 "Non-local sender domain"
        }
    }

    target.remote outbound_delivery {
        limits {
            destination rate 20 1s
            destination concurrency 10
        }
        mx_auth {
            dane
            mtasts {
                cache fs
                fs_dir mtasts_cache/
            }
            local_policy {
                min_tls_level encrypted
                min_mx_level none
            }
        }
    }

    target.queue remote_queue {
        target &outbound_delivery

        autogenerated_msg_domain $(primary_domain)
        bounce {
            destination postmaster $(local_domains) {
                deliver_to &local_routing
            }
            default_destination {
                reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
            }
        }
    }

    imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
        auth &local_authdb
        storage &local_mailboxes
    }
