#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: foxcpp/maddy
  pullPolicy: IfNotPresent
  tag: "0.4.4"

service:
  port:
    name: smtprelay
    port: 25

additionalServices:
  - name: imap
    port: 143
  - name: smtp
    port: 587
  - name: imaptls
    port: 993

ingress:
  enabled: false

strategy:
  type: Recreate

# https://hub.docker.com/r/foxcpp/maddy
env:
  # -- MX hostname
  # MADDY_HOSTNAME: mx.example.org
  # -- Domain to handle messages for
  # MADDY_DOMAIN: example.org

persistence:
  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 5Gi
