{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap to the additionalVolumes */}}
{{- define "maddy.configmap.volume" -}}
name: maddy-config
configMap:
  name: {{ template "common.names.fullname" . }}-config
  defaultMode: 256
  optional: true
{{- end -}}

{{- if eq .Values.config.mode "values" -}}
  {{- $volume := include "maddy.configmap.volume" . | fromYaml -}}
  {{- if $volume -}}
      {{- $additionalVolumes := append .Values.additionalVolumes $volume }}
      {{- $_ := set .Values "additionalVolumes" (deepCopy $additionalVolumes) -}}
  {{- end -}}
{{- end -}}

{{/* Append the configMap volume to the additionalVolumeMounts */}}
{{- define "maddy.configmap.volumeMount" -}}
name: maddy-config
mountPath: /data/maddy.conf
subPath: maddy.conf
{{- end -}}

{{- if eq .Values.config.mode "values" -}}
  {{- $volumeMount := include "maddy.configmap.volumeMount" . | fromYaml -}}
  {{- if $volumeMount -}}
      {{- $additionalVolumeMounts := append .Values.additionalVolumeMounts $volumeMount }}
      {{- $_ := set .Values "additionalVolumeMounts" (deepCopy $additionalVolumeMounts) -}}
  {{- end -}}
{{- end -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
