{{- if eq .Values.config.mode "values" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- range $file, $content := .Values.config.files }}
  {{ $file }}: |-
    {{- $content | nindent 4}}
  {{- end }}
{{- end }}
